- name: install monitoring stack
  hosts: servers
  become: yes
  roles:
  - prometheus
  - grafana

- name: install node-exporter
  hosts: servers
  become: yes
  roles:
  - node-exporter

- name: install docker
  hosts: servers
  become: yes
  roles:
  - docker
